name: Manual workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: npm install newman@5.2.2
      - name: Test
        run: newman run ./API_tests/APITests.postman_collection.json
